# Generated by Django 3.0.3 on 2020-03-01 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customers',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(null=True)),
                ('customer_id', models.UUIDField(primary_key=True, serialize=False)),
                ('first_name', models.TextField(max_length=20)),
                ('last_name', models.TextField(max_length=20)),
                ('gender', models.TextField(choices=[('M', 'Male'), ('F', 'Female'), ('O', 'Other')], max_length=1)),
                ('email', models.EmailField(max_length=254)),
                ('contact_no', models.TextField(max_length=10)),
                ('city', models.TextField(max_length=20)),
                ('state', models.TextField(max_length=20)),
                ('address_line1', models.TextField(max_length=40)),
                ('address_line2', models.TextField(max_length=40, null=True)),
                ('last_seen', models.DateTimeField(null=True)),
            ],
        ),
    ]
