# Generated by Django 3.0.4 on 2020-03-14 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CustomerModel',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('customer_id', models.UUIDField(editable=False, primary_key=True, serialize=False)),
                ('first_name', models.TextField(max_length=30)),
                ('last_name', models.TextField(max_length=30)),
                ('gender', models.TextField(choices=[('M', 'Male'), ('F', 'Female'), ('O', 'Other')], max_length=1)),
                ('email', models.TextField(max_length=50)),
                ('contact_no', models.TextField(max_length=10)),
                ('city', models.TextField(max_length=20)),
                ('state', models.TextField(max_length=20)),
                ('address_line1', models.TextField(max_length=40)),
                ('address_line2', models.TextField(max_length=30, null=True)),
                ('pin_code', models.TextField(max_length=6)),
                ('last_seen', models.DateTimeField(null=True)),
            ],
        ),
    ]
